apiVersion: v1
kind: Service
metadata:
  name: mnist-inference
spec:
  type: NodePort
  selector:
    app: mnist-inference
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
